"use client";
import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import Link from "next/link";
import { CATEGORIES, type Category, type Product, type ProductInput } from "@/types/catalog";
import { isSupabaseReady, supabase } from "@/lib/supabase";
const blank=():ProductInput=>({name:"",category:"Jogos Americanos",sku:"",collection:"",color_name:"",color_hex:"",retail_price:null,wholesale_price:null,image_url:null,image_status:"placeholder",sort_order:0,is_visible:true});
const money=(v:number|null)=>v==null?"—":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
export function AdminClient(){const [products,setProducts]=useState<Product[]>([]),[filter,setFilter]=useState("Todos"),[search,setSearch]=useState(""),[form,setForm]=useState<ProductInput>(blank()),[editing,setEditing]=useState<Product|null>(null),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{if(!supabase)return;const {data,error}=await supabase.from("products").select("*").order("sort_order");if(error)setMessage("Não foi possível carregar os produtos: "+error.message);else setProducts((data as Product[])||[])};useEffect(()=>{load()},[]);
 const list=useMemo(()=>products.filter(p=>(filter==="Todos"||p.category===filter)&&`${p.name} ${p.sku||""} ${p.color_name||""}`.toLowerCase().includes(search.toLowerCase())),[products,filter,search]);
 const change=(key:keyof ProductInput,value:string|boolean|number|null)=>setForm(old=>({...old,[key]:value}));
 async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!supabase)return;setSaving(true);const path=`products/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9.-]/g,"-")}`;const {error}=await supabase.storage.from("product-images").upload(path,file,{upsert:false});if(error){setMessage("Falha no upload: "+error.message);setSaving(false);return;}const {data}=supabase.storage.from("product-images").getPublicUrl(path);setForm(f=>({...f,image_url:data.publicUrl,image_status:"final"}));setSaving(false)}
 function start(product?:Product){setEditing(product||null);setForm(product?{...product}:blank());setOpen(true);setMessage("")}
 async function save(e:FormEvent){e.preventDefault();if(!supabase){setMessage("Adicione as credenciais do Supabase no .env.local para salvar.");return;}setSaving(true);const payload={...form,sku:form.sku||null,collection:form.collection||null,color_name:form.color_name||null,color_hex:form.color_hex||null};const request=editing?supabase.from("products").update(payload).eq("id",editing.id):supabase.from("products").insert(payload);const {error}=await request;if(error)setMessage("Não foi possível salvar: "+error.message);else{setOpen(false);setMessage("Produto salvo no catálogo.");await load()}setSaving(false)}
 async function toggle(product:Product){if(!supabase)return;await supabase.from("products").update({is_visible:!product.is_visible}).eq("id",product.id);load()}
 async function remove(product:Product){if(!supabase||!confirm(`Excluir ${product.name}?`))return;const {error}=await supabase.from("products").delete().eq("id",product.id);if(error)setMessage(error.message);else load()}
 return <main className="admin-page"><header className="admin-top"><Link className="wordmark" href="/">Mesa<span>&amp;</span>Graça</Link><div><Link href="/catalogo">Visualizar catálogo</Link><Link href="/catalogo/imprimir">Exportar PDF</Link><button onClick={()=>start()}>+ Novo produto</button></div></header><section className="admin-heading"><p className="category-label">GESTÃO DE CATÁLOGO</p><h1>Catálogo Mesa<span>&amp;</span>Graça</h1><p>Cadastre e organize suas peças em um só lugar.</p></section><div className="admin-controls"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome, cor ou SKU"/><div>{["Todos",...CATEGORIES].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div>{message&&<p className="admin-message">{message}</p>} {!isSupabaseReady&&<p className="admin-message">Modo de demonstração: conecte o Supabase para persistir produtos e fotos.</p>}<section className="admin-list">{list.length?list.map(p=><article className="admin-item" key={p.id}><div className="admin-thumb">{p.image_url?<img src={p.image_url} alt=""/>:<span>Sem foto</span>}</div><div><b>{p.name}</b><small>{p.category} · {p.color_name||"Sem cor"}</small></div><strong>{money(p.wholesale_price)}</strong><div className="item-actions"><button onClick={()=>start(p)}>Editar</button><button onClick={()=>toggle(p)}>{p.is_visible?"Ocultar":"Mostrar"}</button><button className="danger" onClick={()=>remove(p)}>Excluir</button></div></article>):<div className="no-products">Nenhum produto encontrado.</div>}</section>
 {open&&<div className="modal-backdrop"><form className="product-form" onSubmit={save}><div className="form-head"><div><p className="category-label">{editing?"EDITAR PRODUTO":"NOVO PRODUTO"}</p><h2>{editing?editing.name||"Produto":"Cadastrar produto"}</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><div className="form-grid"><label>Nome<input required value={form.name} onChange={e=>change("name",e.target.value)}/></label><label>Categoria<select value={form.category} onChange={e=>change("category",e.target.value)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>SKU<input value={form.sku||""} onChange={e=>change("sku",e.target.value)}/></label><label>Coleção<input value={form.collection||""} onChange={e=>change("collection",e.target.value)}/></label><label>Cor<input value={form.color_name||""} onChange={e=>change("color_name",e.target.value)}/></label><label>Cor hexadecimal <input placeholder="#C8A2C8" value={form.color_hex||""} onChange={e=>change("color_hex",e.target.value)}/></label><label>Preço varejo<input type="number" step="0.01" value={form.retail_price??""} onChange={e=>change("retail_price",e.target.value?Number(e.target.value):null)}/></label><label>Preço atacado<input type="number" step="0.01" value={form.wholesale_price??""} onChange={e=>change("wholesale_price",e.target.value?Number(e.target.value):null)}/></label><label>Ordem<input type="number" value={form.sort_order} onChange={e=>change("sort_order",Number(e.target.value))}/></label><label className="file-label">Foto<input type="file" accept="image/*" onChange={upload}/>{form.image_url&&<span>✓ Foto selecionada</span>}</label></div><label className="visible"><input type="checkbox" checked={form.is_visible} onChange={e=>change("is_visible",e.target.checked)}/> Mostrar no catálogo</label><button className="save-product" disabled={saving}>{saving?"Salvando…":"Salvar produto"}</button></form></div>}</main>}
